package replay

// maxFixtureDecodedBytes (SEC-038, GR#15) bounds the total number of
// DECOMPRESSED bytes replay.Load will read out of a single fixture's
// .ndjson.gz shard before rejecting it outright (MET-H007) — enforced
// DURING decompression via serialize.NDJSONSerializer.ReadShard's
// maxDecodedBytes parameter, not by decompressing fully and checking
// the result afterward (that would still pay the attack's full
// memory/CPU cost and only report it, which is symptom-silencing, not a
// fix — the SEC-038 acceptance criteria's own framing).
//
// Population (SEC-033's lesson, named explicitly so this bound is never
// mistaken for foundation.serialize's): this constant applies ONLY to
// harness.replay fixtures — a short, deliberately-triggered recording
// of a Command/CommandResult/Event/Delta stream (doc.go's "Recording
// durability" section: "a fixture is a small, short, deliberately-
// triggered recording session ... not a long-running save"). It is NOT
// reused by foundation.serialize's own package (that package's
// NDJSONSerializer.ReadShard now takes its byte budget as a PARAMETER
// precisely so a future, much larger save-loading caller supplies its
// OWN bound rather than inheriting this fixture-sized one, or vice
// versa — a single hardcoded ceiling shared across both populations is
// exactly the mistake SEC-033 made one level down).
//
// Derivation: the only fixture this repository has ever actually
// produced — fixtures/folkestone64-sample.ndjson.gz, generated by
// gen/main.go's one-Subscribe/three-AdvanceTicks/Pause/Resume session —
// is 13,132 bytes ON DISK (checked 2026-08-10; decompressed size is
// necessarily larger but of the same small order — NDJSON+gzip of a
// six-command session, not world state). maxFixtureDecodedBytes is set
// to 16 MiB (16,777,216 bytes): roughly three orders of magnitude of
// headroom above that one real sample's on-disk size (room for a much
// longer scripted session or larger recorded Delta payloads), while
// staying decisively below the SEC-038 PoC's demonstrated ~67 MB
// decompression bomb (forced from a 65 KB compressed file) — the exact
// attack shape reproduced by this package's regression test is
// rejected with orders of magnitude of margin, not a near-miss
// threshold that depends on exact byte counts to trigger.
//
// This is a chosen tolerance, not a spec-cited figure (no §-numbered
// fixture-size budget exists in the master plan) — logged as an ASM-
// per v1.7. Re-derive it if a legitimate fixture ever approaches this
// ceiling (e.g. a much larger successor tile's recorded session, or a
// deliberately long soak-test recording) — the bound existing at all
// matters more than its exact value, but the value itself is not
// permanent.
const maxFixtureDecodedBytes = 16 * 1024 * 1024
