package replay

import (
	"context"
	"path/filepath"
	"runtime"
	"testing"

	"github.com/aaronukgarcia/Metropolis/internal/protocol"
)

// repoFixturesDir locates the repo-root fixtures/ directory relative to
// this test file's own path (runtime.Caller(0)), independent of `go
// test`'s working directory (which is always this package's own source
// directory, three levels below the repo root: internal/harness/replay).
func repoFixturesDir(t *testing.T) string {
	t.Helper()
	_, thisFile, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime.Caller(0) failed")
	}
	// this file's directory is internal/harness/replay; the repo root is
	// three parents up (harness/replay -> harness -> internal -> root).
	dir := filepath.Dir(thisFile)
	root := filepath.Dir(filepath.Dir(filepath.Dir(dir)))
	return filepath.Join(root, "fixtures")
}

// TestSampleFixtureLoadsAndReplays is AC-6: the checked-in
// fixtures/folkestone64-sample fixture (generated by gen/main.go from a
// short H-STUB session) loads successfully and replays cleanly in both
// modes.
func TestSampleFixtureLoadsAndReplays(t *testing.T) {
	dir := repoFixturesDir(t)
	fx, err := Load(dir, "folkestone64-sample")
	if err != nil {
		t.Fatalf("Load(fixtures/folkestone64-sample): %v", err)
	}
	if len(fx.Records) == 0 {
		t.Fatal("sample fixture has zero records")
	}

	// Mode (a): UIPlayer.
	uip, err := NewUIPlayer(fx)
	if err != nil {
		t.Fatalf("NewUIPlayer: %v", err)
	}
	var deltas, events, results int
	for range uip.Deltas() {
		deltas++
	}
	for range uip.Events() {
		events++
	}
	for range uip.Results() {
		results++
	}
	if deltas == 0 && events == 0 && results == 0 {
		t.Error("UIPlayer produced no output from the sample fixture at all")
	}

	// Mode (b): EnginePlayer, replayed against a fake target that
	// answers every command exactly as the fixture recorded (proving the
	// fixture's own commands/results are internally consistent, and that
	// EnginePlayer/CompareResult work end-to-end against real recorded
	// data, not just synthetic test fixtures).
	ep, err := NewEnginePlayer(fx)
	if err != nil {
		t.Fatalf("NewEnginePlayer: %v", err)
	}
	recorded, err := fx.Results()
	if err != nil {
		t.Fatalf("fx.Results: %v", err)
	}
	if len(recorded) == 0 {
		t.Fatal("sample fixture has zero recorded CommandResults")
	}
	answers := make(map[string]protocol.CommandResult, len(recorded))
	for _, r := range recorded {
		answers[string(r.CorrelationID)] = r
	}

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()
	loopDone := make(chan struct{})
	go func() {
		defer close(loopDone)
		runLoop(ctx, ep, func(cmd protocol.Command) protocol.CommandResult {
			return answers[string(cmd.CorrelationID)]
		})
	}()

	cmp, err := ep.Replay(context.Background())
	if err != nil {
		t.Fatalf("Replay: %v", err)
	}
	if !cmp.Matched {
		t.Fatalf("replaying the sample fixture against its own recorded answers did not match: %v", cmp.Diffs)
	}
	cancel()
	<-loopDone
}
