package stub

import "fmt"

// This file is the Folkestone-64 fixture: a handcrafted, deterministic
// 64x64 cell world generated by pure code from a constant seed (AC-3).
// It is NOT a data file — no fixture asset ships with this package,
// dependency-free by construction, per M0-ENG §2.1's "static handcrafted
// world" requirement for H-STUB.
//
// The layout is a stylised cross-section of real Folkestone, evoking
// (north to south, low Y to high Y): the shoreline, the harbour shelf,
// the M20/A20 motorway corridor, and the North Downs escarpment — never
// real OS Terrain 50 data (that's MOD-017, Sprint 3, out of scope here
// per the acceptance criteria).

// FixtureWidth and FixtureHeight are Folkestone-64's fixed dimensions.
const (
	FixtureWidth  = 64
	FixtureHeight = 64
)

// FixtureSeed is the constant seed Folkestone-64 is generated from. It is
// not a random-number seed in the math/rand sense — GenerateFolkestone64
// is a pure function of (x, y, FixtureSeed) via foldSeed below, so the
// same seed always produces byte-identical output (GR#21). The value is
// documentary (a recognisable constant), not load-bearing.
const FixtureSeed uint64 = 0x466F_6C6B_6573_746E // "FolkestN" ASCII-derived

// TerrainKind names one of Folkestone-64's four terrain bands.
type TerrainKind string

const (
	TerrainShore      TerrainKind = "shore"
	TerrainShelf      TerrainKind = "shelf"
	TerrainMotorway   TerrainKind = "motorway"
	TerrainEscarpment TerrainKind = "escarpment"
)

// Cell is one 1x1 tile of the Folkestone-64 grid.
type Cell struct {
	X, Y      int
	Terrain   TerrainKind
	Elevation int
	// Road is the name of the named road segment occupying this cell, or
	// "" if none (most cells).
	Road string
	// Building is the name of the named building occupying this cell, or
	// "" if none (most cells).
	Building string
}

// World is the loaded Folkestone-64 fixture: a Width x Height grid of
// Cells, addressed World.Cells[y][x].
type World struct {
	Width, Height int
	Cells         [][]Cell
}

// roadSegment and buildingMark are the handcrafted named features placed
// onto the generated terrain bands below.
type roadSegment struct {
	name       string
	y          int
	xStart     int
	xEnd       int // inclusive
	vertical   bool
	fixedX     int
	yStartVert int
	yEndVert   int
}

type buildingMark struct {
	name string
	x, y int
}

// namedRoads and namedBuildings are Folkestone-64's "a few named
// roads/buildings" (AC-3) — handcrafted, fixed coordinates, no data file.
var namedRoads = []roadSegment{
	{name: "Sandgate Road", y: 5, xStart: 8, xEnd: 42},
	{name: "A20 Trunk Road", y: 30, xStart: 0, xEnd: 63},
	{name: "Cheriton High Street", vertical: true, fixedX: 20, yStartVert: 12, yEndVert: 27},
}

var namedBuildings = []buildingMark{
	{name: "Folkestone Harbour Arm", x: 5, y: 3},
	{name: "Leas Cliff Hall", x: 15, y: 20},
	{name: "Sandling Station", x: 50, y: 45},
	{name: "Caesars Camp", x: 58, y: 58},
}

// GenerateFolkestone64 builds the fixture world. It is a pure function of
// FixtureSeed and the fixed dimensions above — calling it twice yields
// byte-identical results (GR#21, AC-11); no I/O, no randomness, no wall
// clock.
func GenerateFolkestone64() *World {
	w := &World{Width: FixtureWidth, Height: FixtureHeight}
	w.Cells = make([][]Cell, FixtureHeight)
	for y := 0; y < FixtureHeight; y++ {
		row := make([]Cell, FixtureWidth)
		for x := 0; x < FixtureWidth; x++ {
			row[x] = Cell{
				X:         x,
				Y:         y,
				Terrain:   terrainBandFor(y),
				Elevation: elevationFor(x, y),
			}
		}
		w.Cells[y] = row
	}

	for _, r := range namedRoads {
		if r.vertical {
			for y := r.yStartVert; y <= r.yEndVert; y++ {
				w.Cells[y][r.fixedX].Road = r.name
			}
			continue
		}
		for x := r.xStart; x <= r.xEnd; x++ {
			w.Cells[r.y][x].Road = r.name
		}
	}

	for _, b := range namedBuildings {
		w.Cells[b.y][b.x].Building = b.name
	}

	return w
}

// terrainBandFor maps a row index to Folkestone-64's four handcrafted
// terrain bands, north (low Y, shoreline) to south (high Y, escarpment).
func terrainBandFor(y int) TerrainKind {
	switch {
	case y < 12:
		return TerrainShore
	case y < 28:
		return TerrainShelf
	case y < 36:
		return TerrainMotorway
	default:
		return TerrainEscarpment
	}
}

// elevationFor computes a deterministic elevation for cell (x, y): a base
// ramp by terrain band plus a small, seed-derived, purely deterministic
// texture (foldSeed) — never math/rand, never time-derived (see
// FixtureSeed's doc comment).
func elevationFor(x, y int) int {
	base := 0
	switch terrainBandFor(y) {
	case TerrainShore:
		base = 0
	case TerrainShelf:
		base = 15
	case TerrainMotorway:
		base = 25
	case TerrainEscarpment:
		base = 30 + (y-36)*3 // escarpment climbs steeply toward the south edge
	}
	texture := int(foldSeed(FixtureSeed, x, y) % 5) // 0..4 of deterministic texture
	return base + texture
}

// foldSeed is a small, dependency-free integer hash (a splitmix64-style
// avalanche) used only to give Folkestone-64's elevation a bit of
// deterministic texture. It is pure arithmetic — no math/rand import, no
// global RNG state, no wall clock — so GenerateFolkestone64 stays a pure
// function of its inputs (GR#21, AC-12).
func foldSeed(seed uint64, x, y int) uint64 {
	z := seed ^ (uint64(uint32(x))*0x9E3779B97F4A7C15 + uint64(uint32(y))*0xBF58476D1CE4E5B9)
	z = (z ^ (z >> 30)) * 0xBF58476D1CE4E5B9
	z = (z ^ (z >> 27)) * 0x94D049BB133111EB
	z = z ^ (z >> 31)
	return z
}

// Cell returns the cell at (x, y), or a zero Cell and false if out of
// bounds.
func (w *World) Cell(x, y int) (Cell, bool) {
	if w == nil || y < 0 || y >= w.Height || x < 0 || x >= w.Width {
		return Cell{}, false
	}
	return w.Cells[y][x], true
}

// String renders a one-line summary, useful in test failure messages and
// debug logging.
func (w *World) String() string {
	if w == nil {
		return "stub.World(nil)"
	}
	return fmt.Sprintf("stub.World(%dx%d, seed=%#x)", w.Width, w.Height, FixtureSeed)
}
