// gen-version.mjs -- build-time git-derived version + changelog generator.
//
// FEAT-1972079872 (Command Console version badge + About page).
// GR#2: app version = git describe; NEVER a hand-maintained constant.
//
// Runs `git describe` + `git log` at BUILD time and writes a GITIGNORED
// generated module (src/generated/version.ts) that the app imports. When git
// is unavailable (tarball build, no .git, git not on PATH) we fall back to a
// safe placeholder so the build NEVER breaks -- the fallback is clearly marked
// so a reviewer can tell a real stamp from a degraded one.
//
// SSOT: git. There is no version number to hand-edit here or anywhere in the
// app; a new commit IS the version bump and IS the newest About entry.

import { execFileSync } from 'node:child_process';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { dirname, resolve } from 'node:path';
import { mkdirSync, writeFileSync } from 'node:fs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, '..', '..'); // webconsole/scripts -> repo root
const OUT_FILE = resolve(__dirname, '..', 'src', 'generated', 'version.ts');

// CAP: the About changelog is baked at build time from the last N commits.
// This is a deliberate, documented cap (no-silent-caps rule) -- the About page
// notes it in its footer so a viewer knows the list is bounded, not truncated
// silently. Bump if a fuller history is wanted; it only affects build size.
export const CHANGELOG_COMMIT_CAP = 100;

// Field delimiter for `git log --pretty` output. 0x1f (unit separator) never
// appears in a commit subject or ref name, so splitting is unambiguous.
const SEP = String.fromCharCode(31); // 0x1f unit separator

const FALLBACK = {
  version: 'dev',
  gitAvailable: false,
  generatedAt: new Date().toISOString(),
  changelog: [],
};

function git(args) {
  return execFileSync('git', args, {
    cwd: REPO_ROOT,
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'ignore'],
  }).trim();
}

/**
 * Collect version + changelog from git. Never throws -- returns FALLBACK-shaped
 * data with gitAvailable:false when git can't be read.
 */
export function generate() {
  try {
    const version = git(['describe', '--tags', '--always', '--dirty']) || 'unknown';

    const raw = git([
      'log',
      `-${CHANGELOG_COMMIT_CAP}`,
      `--pretty=format:%h%x1f%s%x1f%cI%x1f%D`,
    ]);

    const changelog = raw
      .split('\n')
      .filter((l) => l.length > 0)
      .map((line) => {
        const [hash, subject, date, refs] = line.split(SEP);
        // %D gives ref names like "HEAD -> main, tag: v1.2.0". Extract a tag if
        // this commit is a milestone/version boundary.
        let tag;
        if (refs) {
          const m = refs.match(/tag:\s*([^,]+)/);
          if (m) tag = m[1].trim();
        }
        return tag ? { hash, subject, date, tag } : { hash, subject, date };
      });

    return {
      version,
      gitAvailable: true,
      generatedAt: new Date().toISOString(),
      changelogCap: CHANGELOG_COMMIT_CAP,
      changelog,
    };
  } catch {
    return { ...FALLBACK, changelogCap: CHANGELOG_COMMIT_CAP, generatedAt: new Date().toISOString() };
  }
}

/** Write src/generated/version.ts from the git data. Returns the data. */
export function writeVersionModule() {
  const data = generate();
  mkdirSync(dirname(OUT_FILE), { recursive: true });

  const banner =
    '// AUTO-GENERATED by webconsole/scripts/gen-version.mjs at build time.\n' +
    '// DO NOT EDIT and DO NOT COMMIT -- this file is gitignored.\n' +
    '// Source of truth is git (GR#2). Regenerated on every build/dev start.\n';

  const body =
    banner +
    '\n' +
    'export interface ChangelogEntry {\n' +
    '  hash: string;\n' +
    '  subject: string;\n' +
    '  date: string;\n' +
    '  tag?: string;\n' +
    '}\n\n' +
    'export interface VersionInfo {\n' +
    '  version: string;\n' +
    '  gitAvailable: boolean;\n' +
    '  generatedAt: string;\n' +
    '  changelogCap: number;\n' +
    '  changelog: ChangelogEntry[];\n' +
    '}\n\n' +
    `// Cap: last ${CHANGELOG_COMMIT_CAP} commits (see gen-version.mjs CHANGELOG_COMMIT_CAP).\n` +
    'export const versionInfo: VersionInfo = ' +
    JSON.stringify(data, null, 2) +
    ';\n\n' +
    'export const APP_VERSION = versionInfo.version;\n' +
    'export const CHANGELOG = versionInfo.changelog;\n';

  writeFileSync(OUT_FILE, body, 'utf8');
  return data;
}

// Allow running directly: `node scripts/gen-version.mjs`
if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  const d = writeVersionModule();
  process.stdout.write(
    `[gen-version] wrote ${OUT_FILE}\n` +
      `  version: ${d.version}${d.gitAvailable ? '' : ' (FALLBACK -- git unavailable)'}\n` +
      `  changelog entries: ${d.changelog.length}\n`
  );
}
