package world

import (
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"testing"

	"github.com/aaronukgarcia/Metropolis/internal/engine/save"
	"github.com/aaronukgarcia/Metropolis/internal/foundation/serialize"
)

// ---------------------------------------------------------------------------
// FEAT-1972079941 inc8 — engine.world save.Participant tests.
//
// Mirrors the inc3 engine.build / inc5 engine.refuse participant suites
// exactly, adapted to engine.world's DURABLE overlay (startCoord/
// milestoneTier/startHeight + the owned-or-prospected tile set with its
// durable simGrid columns owner/zoning/structureRef). The five mandatory
// shapes: field-parity drift (World/tile/simGrid/meta-wire), full round-trip
// (prove-can-fail per field, distinct non-zero values + distinct non-zero
// coords so a dropped field or tile cannot match by coincidence), byte
// determinism (many-key numeric-sorted emission), load-into-non-empty
// (replace not merge), and copyguard-fires + unknown-record-kind rejection.
// Plus the inc8-specific KEY test: a driven world round-trips and the
// DERIVED terrain/landValue RECOMPUTE to the same values after load.
// ---------------------------------------------------------------------------

func ckErrW(t *testing.T, err error) {
	t.Helper()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

// startCoordFixture is the start tile every fixture world roots at.
var startCoordFixture = TileCoord{X: 7, Y: 11}

// ---------------------------------------------------------------------------
// Field-parity drift tests (the "built but not serialized" guard).
// ---------------------------------------------------------------------------

// TestWorldFieldsAllClassified fails the build if any World field is neither
// serialized (covered) nor explicitly excluded (runtime lock / copy-guard).
func TestWorldFieldsAllClassified(t *testing.T) {
	excluded := map[string]string{
		"mu":   "runtime lock, not state",
		"self": "copy-guard pointer, re-armed by construction; a copy is rejected pre-lock",
	}
	// Covered: serialized via worldMetaWire (startCoord/milestoneTier/
	// startHeight) or the per-tile record (tiles -> world.tile).
	covered := map[string]bool{
		"tiles": true, "startCoord": true, "startHeight": true, "milestoneTier": true,
	}
	rt := reflect.TypeOf((*World)(nil)).Elem()
	for i := 0; i < rt.NumField(); i++ {
		name := rt.Field(i).Name
		_, isExcluded := excluded[name]
		if !isExcluded && !covered[name] {
			t.Fatalf("World field %q is neither serialized nor explicitly excluded -- the 'built but not serialized' class this inc forbids", name)
		}
		if isExcluded && covered[name] {
			t.Fatalf("World field %q is listed as BOTH excluded and covered -- pick one", name)
		}
	}
}

// TestTileFieldsClassified asserts every tile field is either carried on the
// wire (durable) or explicitly excluded as DERIVED (regenerated on load).
func TestTileFieldsClassified(t *testing.T) {
	covered := map[string]bool{
		"coord": true, "sim": true, "owned": true, "ownerID": true, "prospected": true,
	}
	excluded := map[string]string{
		"terrain": "DERIVED — synthesizeTerrain/populateTerrainFromHeightmap, pure fn of coord/startHeight, regenerated by ensureTile on load",
		"geology": "DERIVED — deriveGeology(coord), regenerated by ensureTile on load",
		"onLand":  "DERIVED — classifyLandSea(coord), regenerated by ensureTile on load",
	}
	rt := reflect.TypeOf((*tile)(nil)).Elem()
	if rt.NumField() != len(covered)+len(excluded) {
		t.Fatalf("tile has %d fields but %d are classified -- a tile field was added without a wire counterpart or an exclusion", rt.NumField(), len(covered)+len(excluded))
	}
	for i := 0; i < rt.NumField(); i++ {
		name := rt.Field(i).Name
		_, isCov := covered[name]
		_, isExc := excluded[name]
		if !isCov && !isExc {
			t.Fatalf("tile field %q is neither covered nor excluded", name)
		}
		if isCov && isExc {
			t.Fatalf("tile field %q is BOTH covered and excluded -- pick one", name)
		}
	}
}

// TestSimGridFieldsClassified asserts the durable simGrid columns
// (owner/zoning/structureRef) are on the wire and the DERIVED columns
// (landValue + the four overlay-scratch bytes) are explicitly excluded.
func TestSimGridFieldsClassified(t *testing.T) {
	covered := map[string]string{
		"owner":        "Owner",
		"zoning":       "Zoning",
		"structureRef": "StructureRef",
	}
	excluded := map[string]string{
		"landValue": "DERIVED — seeded from terrainQualityFactor by PurchaseTile / recomputed on re-import (BUG-066), a pure fn of terrain; recomputes on load",
		"traffic":   "DERIVED — OverlayScratch recomputed every tick by engine.traffic",
		"utility":   "DERIVED — OverlayScratch recomputed every tick by the utility networks",
		"pollution": "DERIVED — OverlayScratch recomputed every tick",
		"decay":     "DERIVED — OverlayScratch recomputed every tick",
	}
	st := reflect.TypeOf((*simGrid)(nil)).Elem()
	if st.NumField() != len(covered)+len(excluded) {
		t.Fatalf("simGrid has %d fields but %d are classified -- a simGrid column was added without a wire counterpart or an exclusion", st.NumField(), len(covered)+len(excluded))
	}
	wt := reflect.TypeOf((*worldTileWire)(nil)).Elem()
	for i := 0; i < st.NumField(); i++ {
		name := st.Field(i).Name
		if wire, ok := covered[name]; ok {
			if _, ok := wt.FieldByName(wire); !ok {
				t.Fatalf("worldTileWire is missing field %q for simGrid.%s", wire, name)
			}
			continue
		}
		if _, ok := excluded[name]; ok {
			continue
		}
		t.Fatalf("simGrid field %q is neither covered nor excluded", name)
	}
}

// TestWorldMetaWireFieldsMatchScalars asserts the meta wire carries exactly
// the serialized durable scalar/import fields.
func TestWorldMetaWireFieldsMatchScalars(t *testing.T) {
	want := map[string]reflect.Kind{
		"StartCoord":    reflect.Struct,
		"MilestoneTier": reflect.Int,
		"StartHeight":   reflect.Slice,
	}
	mw := reflect.TypeOf((*worldMetaWire)(nil)).Elem()
	if mw.NumField() != len(want) {
		t.Fatalf("worldMetaWire has %d fields but %d serialized scalars are expected", mw.NumField(), len(want))
	}
	for name, kind := range want {
		f, ok := mw.FieldByName(name)
		if !ok {
			t.Fatalf("worldMetaWire is missing field %q", name)
		}
		if f.Type.Kind() != kind {
			t.Fatalf("worldMetaWire.%s has kind %s, want %s", name, f.Type.Kind(), kind)
		}
	}
}

// ---------------------------------------------------------------------------
// Rich-state builders (DISTINCT, NON-ZERO values + DISTINCT NON-ZERO coords,
// so a dropped field or tile cannot round-trip by coincidence). Setup goes
// through the PUBLIC command surface (PurchaseTile/ApplyOwnershipCommand/
// SetStructure/Prospect) so the ORIGINAL's DERIVED landValue is seeded
// exactly as the restore path re-seeds it — the KEY invariant this inc rests
// on.
// ---------------------------------------------------------------------------

// ownedCellSpec sets one distinct owned cell.
type ownedCellSpec struct {
	local        CellLocal
	owner        uint32
	zoning       Zoning
	structureRef uint32
}

func purchaseW(t *testing.T, a *WorldAPI, c TileCoord, buyer uint32) {
	t.Helper()
	res := a.PurchaseTile(PurchaseCommand{CorrelationID: "setup", Tile: c, BuyerID: buyer})
	if !res.Accepted {
		t.Fatalf("PurchaseTile %v rejected: %+v", c, res.Error)
	}
}

func setCellW(t *testing.T, a *WorldAPI, c TileCoord, s ownedCellSpec) {
	t.Helper()
	res := a.ApplyOwnershipCommand(OwnershipCommand{
		CorrelationID: "setup", Tile: c, Local: s.local, NewOwner: s.owner, NewZoning: s.zoning,
	})
	if !res.Accepted {
		t.Fatalf("ApplyOwnershipCommand %v/%v rejected: %+v", c, s.local, res.Error)
	}
	ckErrW(t, a.SetStructure(c, s.local, s.structureRef, "setup"))
}

// injectRichWorld builds a distinct-non-zero durable world: a non-nil
// imported heightmap, a distinct milestone tier, three OWNED tiles at
// distinct non-zero coords (chosen so numeric X ordering differs from lexical
// — X=2 and X=10), each with several distinct owned cells; one
// PROSPECTED-but-unowned tile; and one QUERY-ONLY tile that must NOT be
// serialized (owned=false, prospected=false).
func injectRichWorld(t *testing.T, a *WorldAPI) {
	t.Helper()
	w := a.w
	w.mu.Lock()
	w.milestoneTier = 4
	w.startHeight = slopedHeights(TileSizeCells, 37) // distinct non-flat 200x200 import
	w.mu.Unlock()

	purchaseW(t, a, TileCoord{X: 2, Y: 5}, 100)
	purchaseW(t, a, TileCoord{X: 2, Y: 9}, 200)  // same X, higher Y — tests tie-break by Y
	purchaseW(t, a, TileCoord{X: 10, Y: 3}, 300) // X=10 > X=2 numerically but "10" < "2" lexically

	setCellW(t, a, TileCoord{X: 2, Y: 5}, ownedCellSpec{CellLocal{Row: 1, Col: 1}, 7, ZoningResidential, 11})
	setCellW(t, a, TileCoord{X: 2, Y: 5}, ownedCellSpec{CellLocal{Row: 3, Col: 4}, 9, ZoningCommercial, 13})
	setCellW(t, a, TileCoord{X: 2, Y: 9}, ownedCellSpec{CellLocal{Row: 2, Col: 6}, 21, ZoningIndustrial, 41})
	setCellW(t, a, TileCoord{X: 10, Y: 3}, ownedCellSpec{CellLocal{Row: 5, Col: 5}, 33, ZoningAgricultural, 61})

	// A prospected-but-unowned tile (durable prospect flag, no simGrid).
	ckErrW(t, a.Prospect(TileCoord{X: 4, Y: 4}, "setup"))

	// A query-only tile: terrain gets generated but it is neither owned nor
	// prospected, so it MUST be absent from the save.
	if _, err := a.TileAt(TileCoord{X: 20, Y: 20}, "setup"); err != nil {
		t.Fatalf("query-only TileAt: %v", err)
	}
}

// injectManyTiles forces MANY owned + prospected tiles across a wide coord
// range (X and Y both spanning single- and double-digit values) so a
// lexical-not-numeric sort, or any unsorted emission, would reorder them.
func injectManyTiles(t *testing.T, a *WorldAPI) {
	t.Helper()
	w := a.w
	w.mu.Lock()
	w.milestoneTier = 6
	w.startHeight = slopedHeights(TileSizeCells, 51)
	w.mu.Unlock()

	// 25 owned tiles at (x,y) over a range that mixes 1- and 2-digit coords.
	n := 0
	for x := 0; x < 5; x++ {
		for y := 0; y < 5; y++ {
			c := TileCoord{X: x*3 + 1, Y: y*4 + 2} // X in {1,4,7,10,13}, Y in {2,6,10,14,18}
			purchaseW(t, a, c, uint32(1000+n))
			setCellW(t, a, c, ownedCellSpec{CellLocal{Row: n % 7, Col: (n + 1) % 11}, uint32(n + 1), Zoning(uint8(n % 5)), uint32(n*3 + 5)})
			n++
		}
	}
	// A spread of prospected-only tiles.
	for x := 0; x < 6; x++ {
		ckErrW(t, a.Prospect(TileCoord{X: x*4 + 2, Y: 25}, "setup"))
	}
}

// ---------------------------------------------------------------------------
// Comparison + save/load drivers. Durable equality is defined as equality of
// the production snapshot (meta + numeric-sorted owned-or-prospected tiles
// with their durable columns) — exactly the serialized set.
// ---------------------------------------------------------------------------

func compareWorld(t *testing.T, a, b *World, label string) {
	t.Helper()
	sa, err := a.snapshotForSave()
	ckErrW(t, err)
	sb, err := b.snapshotForSave()
	ckErrW(t, err)
	if !reflect.DeepEqual(sa.meta, sb.meta) {
		t.Fatalf("%s: meta mismatch:\n a=%+v\n b=%+v", label, dumpMeta(sa.meta), dumpMeta(sb.meta))
	}
	if len(sa.tiles) != len(sb.tiles) {
		t.Fatalf("%s: durable tile count %d != %d", label, len(sa.tiles), len(sb.tiles))
	}
	for i := range sa.tiles {
		if !reflect.DeepEqual(sa.tiles[i], sb.tiles[i]) {
			t.Fatalf("%s: tile[%d] mismatch: coord a=%v b=%v owned a=%v b=%v ownerID a=%v b=%v prospected a=%v b=%v (columns differ: %v)",
				label, i, sa.tiles[i].Coord, sb.tiles[i].Coord, sa.tiles[i].Owned, sb.tiles[i].Owned,
				sa.tiles[i].OwnerID, sb.tiles[i].OwnerID, sa.tiles[i].Prospected, sb.tiles[i].Prospected,
				!reflect.DeepEqual(sa.tiles[i].Owner, sb.tiles[i].Owner) || !reflect.DeepEqual(sa.tiles[i].Zoning, sb.tiles[i].Zoning) || !reflect.DeepEqual(sa.tiles[i].StructureRef, sb.tiles[i].StructureRef))
		}
	}
}

// dumpMeta summarises a meta wire without printing the whole 200x200 map.
func dumpMeta(m worldMetaWire) string {
	rows := len(m.StartHeight)
	cols := 0
	if rows > 0 {
		cols = len(m.StartHeight[0])
	}
	return "startCoord=" + itoa(m.StartCoord.X) + "," + itoa(m.StartCoord.Y) +
		" tier=" + itoa(m.MilestoneTier) + " height=" + itoa(rows) + "x" + itoa(cols)
}

func worldStatesEqual(a, b *World) bool {
	sa, ea := a.snapshotForSave()
	sb, eb := b.snapshotForSave()
	if ea != nil || eb != nil {
		return false
	}
	return reflect.DeepEqual(sa, sb)
}

func saveIntoW(t *testing.T, a *WorldAPI, cid string) string {
	t.Helper()
	root := t.TempDir()
	mgr := save.NewManager(root, []save.Participant{NewSaveParticipant(a)}, cid)
	ctx := save.Context{WorldSeed: 42, CreatedAtTick: 100, GameMonth: 3, AppVersion: "test-world"}
	ckErrW(t, mgr.SaveManual(ctx, "det"))
	return root
}

func loadIntoW(t *testing.T, root string, a *WorldAPI, cid string) {
	t.Helper()
	mgr := save.NewManager(root, []save.Participant{NewSaveParticipant(a)}, cid)
	_, _, err := mgr.Load(manualBundleDirW(t, root))
	ckErrW(t, err)
}

func freshW() *WorldAPI { return NewWorldAPI(startCoordFixture) }

// ---------------------------------------------------------------------------
// Round-trip determinism (the bar) + the DERIVED-recompute KEY test.
// ---------------------------------------------------------------------------

func TestWorldParticipant_RoundTrip(t *testing.T) {
	orig := freshW()
	injectRichWorld(t, orig)

	root := saveIntoW(t, orig, "orig")

	reloaded := freshW()
	loadIntoW(t, root, reloaded, "reloaded")
	compareWorld(t, orig.w, reloaded.w, "post-load")

	// Continue identical, deterministic durable operations on BOTH and assert
	// they stay equal: a divergent restore would surface the moment new work
	// builds on it.
	continueWorld(t, orig)
	continueWorld(t, reloaded)
	compareWorld(t, orig.w, reloaded.w, "post-continue")
}

func continueWorld(t *testing.T, a *WorldAPI) {
	t.Helper()
	purchaseW(t, a, TileCoord{X: 15, Y: 15}, 999)
	setCellW(t, a, TileCoord{X: 15, Y: 15}, ownedCellSpec{CellLocal{Row: 9, Col: 9}, 55, ZoningCommercial, 77})
	ckErrW(t, a.Prospect(TileCoord{X: 1, Y: 1}, "cont"))
}

// TestWorldParticipant_DerivedRecomputesAfterLoad is the inc8 KEY test: after
// a round trip into a FRESH world, the DERIVED terrain (elevation/slope/
// surface) and the DERIVED landValue RECOMPUTE to the same values as the
// original — proving it is correct NOT to serialize them (they are pure
// functions of the restored coord + startHeight), and that the durable
// ownership/zoning/structure state restored exactly.
func TestWorldParticipant_DerivedRecomputesAfterLoad(t *testing.T) {
	orig := freshW()
	injectRichWorld(t, orig)
	root := saveIntoW(t, orig, "orig")

	reloaded := freshW()
	loadIntoW(t, root, reloaded, "reloaded")

	// Every cell of an owned tile: terrain + landValue + durable fields must
	// match between orig and reloaded, cell for cell.
	for _, c := range []TileCoord{{X: 2, Y: 5}, {X: 2, Y: 9}, {X: 10, Y: 3}} {
		oc, err := orig.TileCells(c, "cmp-o")
		ckErrW(t, err)
		rc, err := reloaded.TileCells(c, "cmp-r")
		ckErrW(t, err)
		if len(oc) != len(rc) {
			t.Fatalf("tile %v cell count %d != %d", c, len(oc), len(rc))
		}
		for i := range oc {
			if oc[i] != rc[i] {
				t.Fatalf("tile %v cell %d differs after load:\n orig=%+v\n reld=%+v", c, i, oc[i], rc[i])
			}
		}
		// LandValue must be non-zero somewhere (proves it recomputed, not left zero).
		anyLV := false
		for i := range rc {
			if rc[i].LandValue != 0 {
				anyLV = true
				break
			}
		}
		if !anyLV {
			t.Fatalf("tile %v: reloaded landValue is all zero -- DERIVED recompute did not run", c)
		}
	}

	// The start tile's terrain came from the imported heightmap; it must
	// regenerate identically from the restored startHeight.
	oStart, err := orig.CellAt(startCoordFixture, CellLocal{Row: 100, Col: 100}, "s-o")
	ckErrW(t, err)
	rStart, err := reloaded.CellAt(startCoordFixture, CellLocal{Row: 100, Col: 100}, "s-r")
	ckErrW(t, err)
	if oStart != rStart {
		t.Fatalf("start-tile cell differs after load:\n orig=%+v\n reld=%+v", oStart, rStart)
	}

	// The prove-can-fail guard for this test: if landValue were WRONGLY
	// serialized-and-restored from a stale value rather than recomputed, a
	// re-import against different terrain would strand it — but that is the
	// BUG-066 path, already covered. Here we simply assert full durable parity.
	compareWorld(t, orig.w, reloaded.w, "derived-recompute")
}

// TestWorldParticipant_ProveCanFail mutates each durable field family on one
// pristine reload and asserts it diverges from a second pristine reload of the
// SAME bytes -- proving the comparison is discriminating for every field.
func TestWorldParticipant_ProveCanFail(t *testing.T) {
	orig := freshW()
	injectRichWorld(t, orig)
	root := saveIntoW(t, orig, "orig")

	cases := []struct {
		name   string
		mutate func(a *WorldAPI)
	}{
		{"milestoneTier", func(a *WorldAPI) { a.w.mu.Lock(); a.w.milestoneTier++; a.w.mu.Unlock() }},
		{"startCoord", func(a *WorldAPI) { a.w.mu.Lock(); a.w.startCoord.X++; a.w.mu.Unlock() }},
		{"startHeight", func(a *WorldAPI) { a.w.mu.Lock(); a.w.startHeight[0][0] += 100; a.w.mu.Unlock() }},
		{"tile.ownerID", func(a *WorldAPI) { a.w.mu.Lock(); a.w.tiles[TileCoord{X: 2, Y: 5}].ownerID = 0; a.w.mu.Unlock() }},
		{"tile.owned", func(a *WorldAPI) { a.w.mu.Lock(); a.w.tiles[TileCoord{X: 2, Y: 5}].owned = false; a.w.mu.Unlock() }},
		{"tile.prospected", func(a *WorldAPI) { a.w.mu.Lock(); a.w.tiles[TileCoord{X: 4, Y: 4}].prospected = false; a.w.mu.Unlock() }},
		{"sim.owner", func(a *WorldAPI) {
			a.w.mu.Lock()
			a.w.tiles[TileCoord{X: 2, Y: 5}].sim.owner[localIndex(1, 1)] = 0
			a.w.mu.Unlock()
		}},
		{"sim.zoning", func(a *WorldAPI) {
			a.w.mu.Lock()
			a.w.tiles[TileCoord{X: 2, Y: 9}].sim.zoning[localIndex(6, 2)] = ZoningNone
			a.w.mu.Unlock()
		}},
		{"sim.structureRef", func(a *WorldAPI) {
			a.w.mu.Lock()
			a.w.tiles[TileCoord{X: 10, Y: 3}].sim.structureRef[localIndex(5, 5)] = 0
			a.w.mu.Unlock()
		}},
		{"drop-tile", func(a *WorldAPI) { a.w.mu.Lock(); delete(a.w.tiles, TileCoord{X: 2, Y: 9}); a.w.mu.Unlock() }},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			mutated := freshW()
			loadIntoW(t, root, mutated, "mutated")
			pristine := freshW()
			loadIntoW(t, root, pristine, "pristine")
			compareWorld(t, mutated.w, pristine.w, "pre-mutation")
			c.mutate(mutated)
			if worldStatesEqual(mutated.w, pristine.w) {
				t.Fatalf("prove-can-fail: mutating %s did not diverge from a pristine reload -- the field may be dropped or the compare is blind to it", c.name)
			}
		})
	}
}

// ---------------------------------------------------------------------------
// Byte determinism.
// ---------------------------------------------------------------------------

func TestWorldParticipant_ByteDeterminism(t *testing.T) {
	a1 := freshW()
	injectRichWorld(t, a1)
	root1 := saveIntoW(t, a1, "run1")

	a2 := freshW()
	injectRichWorld(t, a2)
	root2 := saveIntoW(t, a2, "run2")

	assertBundlesByteIdenticalW(t, root1, root2)
}

// TestWorldAttack_ManyKeyByteDeterminism forces MANY tiles into the map and
// asserts two saves of the same state are byte-identical -- proves NUMERIC
// coord-sorted emission, not just single-tile determinism. Two independently
// built maps iterate in different orders, so an unsorted (or lexically-sorted)
// emission would differ.
func TestWorldAttack_ManyKeyByteDeterminism(t *testing.T) {
	a1 := freshW()
	injectManyTiles(t, a1)
	root1 := saveIntoW(t, a1, "run1")

	a2 := freshW()
	injectManyTiles(t, a2)
	root2 := saveIntoW(t, a2, "run2")

	if got := durableTileCount(t, a1); got < 20 {
		t.Fatalf("test setup: only %d durable tiles -- too few to force map reorder", got)
	}
	assertBundlesByteIdenticalW(t, root1, root2)
}

// TestWorldAttack_ManyKeyRoundTrip asserts the many-key state round-trips
// exactly.
func TestWorldAttack_ManyKeyRoundTrip(t *testing.T) {
	orig := freshW()
	injectManyTiles(t, orig)
	root := saveIntoW(t, orig, "orig")

	reloaded := freshW()
	loadIntoW(t, root, reloaded, "reloaded")

	compareWorld(t, orig.w, reloaded.w, "many-key-load")
}

// TestWorldAttack_NumericCoordOrder asserts the emitted tile records are in
// STRICTLY-ASCENDING NUMERIC coord order (X then Y) -- and specifically that a
// double-digit X sorts AFTER a single-digit X (the lexical-vs-numeric gap a
// prior finding caught: "10" < "2" lexically).
func TestWorldAttack_NumericCoordOrder(t *testing.T) {
	orig := freshW()
	injectRichWorld(t, orig)
	snap, err := orig.w.snapshotForSave()
	ckErrW(t, err)
	if len(snap.tiles) < 3 {
		t.Fatalf("need >=3 tiles to test order, got %d", len(snap.tiles))
	}
	sawX10 := false
	sawX2 := false
	var x10Idx, x2LastIdx int
	for i := 1; i < len(snap.tiles); i++ {
		prev, cur := snap.tiles[i-1].Coord, snap.tiles[i].Coord
		if !lessTileCoord(prev, cur) {
			t.Fatalf("tiles not strictly numeric-ascending at %d: %v then %v", i, prev, cur)
		}
	}
	for i, tw := range snap.tiles {
		if tw.Coord.X == 2 {
			sawX2 = true
			x2LastIdx = i
		}
		if tw.Coord.X == 10 {
			sawX10 = true
			x10Idx = i
		}
	}
	if !sawX2 || !sawX10 {
		t.Fatalf("expected both X=2 and X=10 tiles present (numeric-vs-lexical probe)")
	}
	if x10Idx <= x2LastIdx {
		t.Fatalf("numeric order broken: X=10 tile at idx %d is not after the last X=2 tile at idx %d (lexical sort would put X=10 first)", x10Idx, x2LastIdx)
	}
}

// ---------------------------------------------------------------------------
// Load-into-non-empty (full replace, not merge) + copyguard + unknown-kind.
// ---------------------------------------------------------------------------

// TestWorldAttack_LoadIntoNonEmptyFullyReplaces: a Load into a world that
// already holds DIFFERENT durable state must fully overwrite it (Handler
// resets), never merge.
func TestWorldAttack_LoadIntoNonEmptyFullyReplaces(t *testing.T) {
	orig := freshW()
	injectRichWorld(t, orig)
	root := saveIntoW(t, orig, "orig")

	// Pre-populate the target with a DIFFERENT, larger state including a GHOST
	// owned tile the saved state never touches.
	target := freshW()
	injectManyTiles(t, target)
	const ghostX, ghostY = 13, 18 // present in injectManyTiles, absent from injectRichWorld
	target.w.mu.RLock()
	_, ghostPresent := target.w.tiles[TileCoord{X: ghostX, Y: ghostY}]
	target.w.mu.RUnlock()
	if !ghostPresent {
		t.Fatalf("test setup: ghost tile not present on target pre-load")
	}
	orig.w.mu.RLock()
	_, ghostInOrig := orig.w.tiles[TileCoord{X: ghostX, Y: ghostY}]
	orig.w.mu.RUnlock()
	if ghostInOrig {
		t.Fatalf("test setup: saved state unexpectedly holds the ghost tile")
	}

	loadIntoW(t, root, target, "target")

	target.w.mu.RLock()
	gt := target.w.tiles[TileCoord{X: ghostX, Y: ghostY}]
	target.w.mu.RUnlock()
	if gt != nil && (gt.owned || gt.prospected) {
		t.Fatalf("ghost tile survived load as durable -- Handler merged instead of replacing")
	}
	if got, want := durableTileCount(t, target), durableTileCount(t, orig); got != want {
		t.Fatalf("durable tile count %d != saved %d -- merge, not replace", got, want)
	}
	compareWorld(t, orig.w, target.w, "load-into-nonempty")
}

// TestWorldAttack_CopyguardFiresOnParticipant: a struct-copied World's
// participant must fail closed on Kind/Source/Handler.
func TestWorldAttack_CopyguardFiresOnParticipant(t *testing.T) {
	orig := freshW()
	injectRichWorld(t, orig)

	// A value-copied World (w2Copy is the same-package unsafe byte-copy used by
	// the BUG-064 regression tests): self still points at the ORIGINAL.
	copied := w2Copy(orig.w)
	sp := NewSaveParticipant(&WorldAPI{w: copied})

	if sp.Kind() != "" {
		t.Fatalf("copied participant Kind() = %q, want empty (guard should fire)", sp.Kind())
	}
	src := sp.Source()
	if _, _, err := src(); err == nil {
		t.Fatalf("copied participant Source() first pull returned nil error -- guard did not fire")
	}
	h := sp.Handler()
	if err := h(serialize.Record{}); err == nil {
		t.Fatalf("copied participant Handler() returned nil error -- guard did not fire")
	}
	// And the ORIGINAL still works.
	if NewSaveParticipant(orig).Kind() != KindWorld {
		t.Fatalf("original participant Kind() broken")
	}
}

// TestWorldAttack_UnknownRecordKindRejected: an unrecognised record kind fails
// loud and closed, never a silent partial load.
func TestWorldAttack_UnknownRecordKindRejected(t *testing.T) {
	a := freshW()
	h := NewSaveParticipant(a).Handler()
	if err := h(serialize.Record{Kind: "world.bogus", Data: []byte(`{}`)}); err == nil {
		t.Fatalf("Handler accepted an unknown record kind -- want a loud error")
	}
}

// TestWorldAttack_ShortColumnRejected: a corrupted tile record whose durable
// column is not exactly CellsPerTile long is rejected, never silently
// truncated into a partially-zeroed tile.
func TestWorldAttack_ShortColumnRejected(t *testing.T) {
	a := freshW()
	h := NewSaveParticipant(a).Handler()
	// Meta first (Handler resets on the first record; a meta keeps the reset
	// path identical to a real load).
	ckErrW(t, h(serialize.Record{Kind: recWorldMeta, Data: []byte(`{"startCoord":{"X":7,"Y":11},"milestoneTier":1,"startHeight":null}`)}))
	// An owned tile whose owner column is length 3 (not CellsPerTile).
	bad := `{"coord":{"X":2,"Y":2},"owned":true,"ownerID":1,"prospected":false,"owner":[1,2,3],"zoning":[0,0,0],"structureRef":[0,0,0]}`
	if err := h(serialize.Record{Kind: recWorldTile, Data: []byte(bad)}); err == nil {
		t.Fatalf("Handler accepted a short durable column -- want a loud error")
	}
}

// ---------------------------------------------------------------------------
// Helpers.
// ---------------------------------------------------------------------------

func durableTileCount(t *testing.T, a *WorldAPI) int {
	t.Helper()
	s, err := a.w.snapshotForSave()
	ckErrW(t, err)
	return len(s.tiles)
}

func assertBundlesByteIdenticalW(t *testing.T, root1, root2 string) {
	t.Helper()
	dir1 := manualBundleDirW(t, root1)
	dir2 := manualBundleDirW(t, root2)
	files1 := allFilesW(t, dir1)
	files2 := allFilesW(t, dir2)
	if len(files1) == 0 {
		t.Fatalf("test setup: bundle %q has no files", dir1)
	}
	if !reflect.DeepEqual(files1, files2) {
		t.Fatalf("bundle file sets differ: run1=%v run2=%v", files1, files2)
	}
	for _, rel := range files1 {
		b1, err := os.ReadFile(filepath.Join(dir1, rel))
		ckErrW(t, err)
		b2, err := os.ReadFile(filepath.Join(dir2, rel))
		ckErrW(t, err)
		if string(b1) != string(b2) {
			t.Fatalf("file %q differs byte-for-byte between two saves of the same deterministic world state", rel)
		}
	}
}

func manualBundleDirW(t *testing.T, root string) string {
	t.Helper()
	var found string
	err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if !info.IsDir() && info.Name() == "header.json" {
			found = filepath.Dir(path)
		}
		return nil
	})
	ckErrW(t, err)
	if found == "" {
		t.Fatalf("no bundle (header.json) found under %q", root)
	}
	return found
}

func allFilesW(t *testing.T, dir string) []string {
	t.Helper()
	var out []string
	err := filepath.Walk(dir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() {
			return nil
		}
		rel, err := filepath.Rel(dir, path)
		if err != nil {
			return err
		}
		out = append(out, rel)
		return nil
	})
	ckErrW(t, err)
	sort.Strings(out)
	return out
}
