// attack-feat804-round.test.mjs — INDEPENDENT Destructive round 1 pins for
// FEAT-2326609804 "per-tile mode split" (attacker: opus-round-feat804,
// authority docs/planning/acceptance/FEAT-2326609804.md).
//
// These are the ATTACKER's lasting pins: every one of them is a property the
// author's own suite (webconsole/test/trafficModeSplit.test.mjs) did NOT
// pin, or pinned only structurally. No timing assertion lives here (perf
// numbers belong in the round note, not in CI).
//
// The round's SURVIVING mutants (filed as blockers, deliberately NOT pinned
// here because the current code would go red):
//   * the doc's AC-7 "missing-table not fail-closed" mutant — the author's
//     AC-7 test asserts `typeof {}.walkAccessRadiusMetres === 'undefined'`
//     on a literal it writes itself and never touches the loader. The two
//     RED-PROOFs below show that test IS practical with this repo's own
//     testsupport/mutant.mjs shadow-copy helper, and they are the durable
//     replacement.
//   * the aliasing defect (perTileLocalModeShareOf hands out the live
//     module-level JSON table row object) and the tier-blind density band —
//     both are real behaviour today, so they are bugs, not pins.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { runWithMutant, runBaselineProbe } from '../testsupport/mutant.mjs';
import { SPECS } from '../src/sim/data.ts';
import {
  tileLocalAccessBandOf,
  perTileLocalModeShareOf,
  realisedCityWideModeShareOf,
  landUseDensityBandFor,
} from '../src/sim/trafficModeSplit.ts';
import { modeShareOf, ladderPointOf, demandForecastOf } from '../src/sim/trafficDemand.ts';
import { initialState } from '../src/sim/engine.ts';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, '..', '..');
const LOCAL = JSON.parse(readFileSync(path.join(repoRoot, 'data', 'traffic', 'mode_split_local.json'), 'utf8'));
const BY_DENSITY = JSON.parse(readFileSync(path.join(repoRoot, 'data', 'traffic', 'mode_share_by_density.json'), 'utf8'));

function board(buildings, population = 0) {
  const base = initialState();
  let maxId = 0;
  for (const bb of buildings) if (bb.id > maxId) maxId = bb.id;
  return { ...base, unlockedAll: true, buildings, nextId: maxId + 1, roadNotice: null, population };
}
const b = (id, spec, x, y) => ({ id, spec, x, y });

// ── DATA-TABLE PINS ─────────────────────────────────────────────────────────
// mode_split_local.json's landUseDensityMapping was machine-generated by an
// UNCOMMITTED scratch script; its meta note states the rule only in prose
// ("buckets every SPECS id that carries residents or jobs by (residents+jobs)
// magnitude into mode_share_by_density.json's own 8 band ids") and never
// states the bucket boundaries. These pins make that prose mechanically
// checkable so a later hand-edit cannot silently break the stated rule.

test('round: landUseDensityMapping covers EXACTLY the residents/jobs-bearing SPECS set — no gap, no orphan', () => {
  const need = [];
  for (const [id, sp] of Object.entries(SPECS)) if (sp.residents != null || sp.jobs != null) need.push(id);
  const mapped = Object.keys(LOCAL.landUseDensityMapping);
  assert.deepEqual(need.filter((x) => !mapped.includes(x)), [], 'a residents/jobs spec with no mapping entry (the module throws MET-V957 at load)');
  assert.deepEqual(mapped.filter((x) => !need.includes(x)), [], 'an orphan mapping entry for a spec that generates no demand');
  assert.equal(need.length, 41);
});

test('round: the mapping is MONOTONE in (residents+jobs) against mode_share_by_density.json band order (the generator rule, otherwise unrecorded)', () => {
  const order = BY_DENSITY.bands.map((x) => x.id);
  const rows = Object.entries(LOCAL.landUseDensityMapping).map(([id, band]) => {
    const sp = SPECS[id];
    assert.ok(order.includes(band), `band '${band}' for '${id}' is not a mode_share_by_density.json band id`);
    return { id, mag: (sp.residents || 0) + (sp.jobs || 0), rank: order.indexOf(band) };
  });
  rows.sort((x, y) => x.mag - y.mag);
  const violations = [];
  for (let i = 1; i < rows.length; i++) if (rows[i].rank < rows[i - 1].rank) violations.push(`${rows[i - 1].id}->${rows[i].id}`);
  assert.deepEqual(violations, [], 'a smaller building mapped to a DENSER band than a larger one — the stated derivation rule is broken');
});

test('round: every table vector sums to 1 within 1e-12 (the loader only demands 1e-6, which is a real hole in AC-4 renormalisation)', () => {
  for (const [key, vector] of Object.entries(LOCAL.table)) {
    assert.deepEqual(Object.keys(vector).slice().sort(), LOCAL.modeIds.slice().sort(), `table['${key}'] keys != modeIds`);
    let sum = 0;
    for (const v of Object.values(vector)) sum += v;
    assert.ok(Math.abs(sum - 1) < 1e-12, `table['${key}'] sums to ${sum}`);
  }
  assert.ok(Object.keys(LOCAL.table).length >= 16);
});

test('round: the city-wide fallback row has EXACTLY the same mode ids as modeIds — nothing is silently dropped by the rollup', () => {
  // realisedCityWideModeShareOf accumulates over MODE_IDS only and reads
  // `vector[id] ?? 0`; a city row carrying a mode absent from modeIds would
  // be silently zeroed and the renormalisation would HIDE it (the vector
  // still sums to 1). Pin the two key sets equal.
  for (const pop of [0, 500, 50000, 2000000]) {
    const s = board([b(1, 'res_hut', 5, 5)], pop);
    const city = modeShareOf(ladderPointOf(s));
    assert.deepEqual(Object.keys(city).slice().sort(), LOCAL.modeIds.slice().sort(), `city row at pop ${pop} does not match modeIds`);
  }
});

// ── BUILD-SENSITIVITY PINS (the whole point of the increment) ──────────────

test('round: at IDENTICAL population, building a rail line moves the realised city-wide split while the city-level split does not move at all', () => {
  const without = board([b(1, 'res_block', 10, 10), b(2, 'res_block', 40, 40)], 200);
  const withRail = board([b(1, 'res_block', 10, 10), b(2, 'res_block', 40, 40), b(3, 'rail', 10, 11)], 200);
  const a = realisedCityWideModeShareOf(without);
  const c = realisedCityWideModeShareOf(withRail);
  assert.notDeepEqual(a, c, 'the realised split must respond to built infrastructure — otherwise inc9 re-coupling is still a population bonus');
  assert.ok(c.car < a.car, `car share must fall with rail access (${a.car} -> ${c.car})`);
  assert.ok(c.bus > a.bus, `bus share must rise with rail access (${a.bus} -> ${c.bus})`);
  // The control: the OLD population-keyed vector is identical in both cities.
  assert.deepEqual(modeShareOf(ladderPointOf(without)), modeShareOf(ladderPointOf(withRail)));
  // And the access band actually differs (not a coincidental numeric shift).
  assert.equal(tileLocalAccessBandOf(without).get('10,10'), 'local_access_none');
  assert.equal(tileLocalAccessBandOf(withRail).get('10,10'), 'local_access_medium');
});

test('round: at IDENTICAL population, a different LAND-USE mix moves the realised city-wide split', () => {
  const huts = board([b(1, 'res_hut', 10, 10), b(2, 'res_hut', 12, 12)], 16);
  const estate = board([b(1, 'res_estate', 10, 10)], 16);
  assert.notDeepEqual(realisedCityWideModeShareOf(huts), realisedCityWideModeShareOf(estate));
  assert.deepEqual(modeShareOf(ladderPointOf(huts)), modeShareOf(ladderPointOf(estate)), 'control: the population-keyed row is the same for both');
});

test('round: determinism — three independently constructed, equal states give byte-identical results', () => {
  const mk = () => board([b(1, 'res_block', 10, 10), b(2, 'rail', 10, 11), b(3, 'off_tower', 30, 30)], 500);
  const city = [0, 1, 2].map(() => JSON.stringify(realisedCityWideModeShareOf(mk())));
  assert.equal(city[0], city[1]);
  assert.equal(city[1], city[2]);
  const perTile = [0, 1, 2].map(() => JSON.stringify([...perTileLocalModeShareOf(mk())].sort()));
  assert.equal(perTile[0], perTile[1]);
  assert.equal(perTile[1], perTile[2]);
  const bands = [0, 1, 2].map(() => JSON.stringify([...tileLocalAccessBandOf(mk())].sort()));
  assert.equal(bands[0], bands[1]);
  assert.equal(bands[1], bands[2]);
});

test('round: the zero-demand degenerate path returns the city row EXACTLY (the real New Game ships 0 demand tiles — any perf/behaviour claim measured on it is vacuous)', () => {
  const ng = { ...initialState(), population: 50000 };
  assert.equal(demandForecastOf(ng).length, 0, 'initialState() has no residents/jobs-bearing building — this fixture cannot exercise the module');
  assert.equal(tileLocalAccessBandOf(ng).size, 0);
  assert.deepEqual(realisedCityWideModeShareOf(ng), modeShareOf(ladderPointOf(ng)));
});

// ── FAIL-CLOSED LOADER RED-PROOFS (the AC-7 check the author suite skipped) ──

const CHILD = [
  "let threw = '';",
  "try { await import('./sim/trafficModeSplit.ts'); } catch (e) { threw = String(e && e.message || e); }",
  "console.log(JSON.stringify({ threw }));",
].join('\n');

test('round RED-PROOF (non-vacuity): the loader probe reaches its marker against an UNMUTATED shadow copy', () => {
  const out = runBaselineProbe({
    targetRelPath: path.join('sim', 'traffic-data', 'mode_split_local.json'),
    childBody: CHILD,
    timeoutMs: 120000,
  });
  const { threw } = JSON.parse(out.trim().split('\n').pop());
  assert.equal(threw, '', `the module must import cleanly when the table is intact, got: ${threw}`);
});

test('round RED-PROOF: a mode_split_local.json with walkAccessRadiusMetres removed makes the module throw MET-V958 at load (AC-7 fail-closed)', () => {
  const out = runWithMutant({
    targetRelPath: path.join('sim', 'traffic-data', 'mode_split_local.json'),
    mutate: (original) => {
      const j = JSON.parse(original);
      assert.ok(typeof j.walkAccessRadiusMetres === 'number', 'RED-PROOF setup: walkAccessRadiusMetres not present');
      delete j.walkAccessRadiusMetres;
      return JSON.stringify(j, null, 2);
    },
    childBody: CHILD,
    timeoutMs: 120000,
  });
  const { threw } = JSON.parse(out.trim().split('\n').pop());
  assert.match(threw, /MET-V958/, `expected a MET-V958 load-time throw, got: ${threw || '(no throw — the loader is NOT fail-closed)'}`);
});

test('round RED-PROOF: a mode_split_local.json missing a residents/jobs spec mapping throws MET-V957 at load (AC-1 completeness)', () => {
  const out = runWithMutant({
    targetRelPath: path.join('sim', 'traffic-data', 'mode_split_local.json'),
    mutate: (original) => {
      const j = JSON.parse(original);
      assert.ok('res_hut' in j.landUseDensityMapping, 'RED-PROOF setup: res_hut mapping not present');
      delete j.landUseDensityMapping.res_hut;
      return JSON.stringify(j, null, 2);
    },
    childBody: CHILD,
    timeoutMs: 120000,
  });
  const { threw } = JSON.parse(out.trim().split('\n').pop());
  assert.match(threw, /MET-V957/, `expected a MET-V957 load-time throw, got: ${threw || '(no throw)'}`);
  assert.match(threw, /res_hut/);
});

test('round RED-PROOF: a table row whose vector no longer sums to 1 throws MET-V959 at load (AC-7 vector validity)', () => {
  const out = runWithMutant({
    targetRelPath: path.join('sim', 'traffic-data', 'mode_split_local.json'),
    mutate: (original) => {
      const j = JSON.parse(original);
      const key = Object.keys(j.table)[0];
      j.table[key].car += 0.25;
      return JSON.stringify(j, null, 2);
    },
    childBody: CHILD,
    timeoutMs: 120000,
  });
  const { threw } = JSON.parse(out.trim().split('\n').pop());
  assert.match(threw, /MET-V959/, `expected a MET-V959 load-time throw, got: ${threw || '(no throw)'}`);
});

// ── AC-8 scope boundary ─────────────────────────────────────────────────────

test('round: no module under webconsole/src consumes the three new exports (AC-8 "no consumer yet")', () => {
  // Structural, but over the WHOLE src tree rather than trafficRewards.ts alone.
  const files = [];
  const walk = (dir) => {
    for (const e of readdirSync(dir, { withFileTypes: true })) {
      const p = path.join(dir, e.name);
      if (e.isDirectory()) walk(p);
      else if (/\.tsx?$/.test(e.name)) files.push(p);
    }
  };
  walk(path.join(repoRoot, 'webconsole', 'src'));
  const offenders = [];
  for (const f of files) {
    if (path.basename(f) === 'trafficModeSplit.ts') continue;
    const src = readFileSync(f, 'utf8');
    if (/realisedCityWideModeShareOf|perTileLocalModeShareOf|tileLocalAccessBandOf/.test(src)) offenders.push(path.relative(repoRoot, f));
  }
  assert.deepEqual(offenders, [], 'AC-8 forbids a live consumer this increment');
});

// ═══════════════════════════════════════════════════════════════════════════
// ROUND 2 PINS (attacker: opus-reround-feat804) — appended after the r1
// blockers BUG-985..992 were reworked. The r1 header above describes the
// r1 state; the aliasing defect and the tier-blind band ARE fixed now and
// are pinned by the author's suite, so the "deliberately not pinned" note
// above applies only to r1's history.
//
// Independent r2 mutant table (scratch copy of the REAL src file, .bak kept
// OUTSIDE the repo, md5-verified identical after every run; author suite +
// this file as the observer): M1 tier ignored RED / M2 walk radius
// unbounded RED / M3 always city row RED / M4 tile-count weighting RED /
// M5 a mode dropped from every per-tile vector RED / M6 aliasing
// reintroduced RED / M7 hardcoded radius 8 RED / M8 reversed iteration RED
// / M9 renormalisation dropped SURVIVED — M9 is a PROVEN-EQUIVALENT mutant
// (sum === totalWeight exactly when every vector sums to 1, which the
// loader now enforces at 1e-9), matching the author's own honest
// disclosure rather than contradicting it.
// ═══════════════════════════════════════════════════════════════════════════

test('round2: the doc\'s literal AC-5 (per-CLASS totals identical) is UNSATISFIABLE on a differentiated fixture, while the GRAND TOTAL conserves exactly', () => {
  // The point of this pin is to stop a future increment "restoring" the
  // doc's per-class invariant: per-tile differentiation is the whole
  // feature, so per-class totals MUST diverge from the population-keyed
  // city computation. Measured here, not asserted from memory.
  const s = board([b(1, 'res_hut', 80, 80), b(2, 'rail', 80, 81), b(3, 'res_hut', 600, 600)], 50);
  const tiles = demandForecastOf(s);
  assert.ok(tiles.length >= 2, 'fixture precondition: at least two demand tiles');
  const perTile = perTileLocalModeShareOf(s);
  const cityRow = modeShareOf(ladderPointOf(s));
  const ids = Object.keys(cityRow);
  const pt = {}, cw = {};
  for (const id of ids) { pt[id] = 0; cw[id] = 0; }
  let trips = 0;
  for (const t of tiles) {
    const v = perTile.get(`${t.x},${t.y}`);
    trips += t.personTrips;
    for (const id of ids) { pt[id] += (v[id] ?? 0) * t.personTrips; cw[id] += (cityRow[id] ?? 0) * t.personTrips; }
  }
  const worst = Math.max(...ids.map((id) => Math.abs(pt[id] - cw[id])));
  assert.ok(worst > 1e-9, `per-class divergence must be REAL (got ${worst}) — if this ever goes to zero the per-tile split has stopped differentiating`);
  let sPt = 0, sCw = 0;
  for (const id of ids) { sPt += pt[id]; sCw += cw[id]; }
  assert.ok(Math.abs(sPt - trips) < 1e-9, `per-tile grand total ${sPt} must equal person-trips ${trips}`);
  assert.ok(Math.abs(sCw - trips) < 1e-9, `city-wide grand total ${sCw} must equal person-trips ${trips}`);
});

test('round2 (BUG-989): the density-band threshold table is strictly ascending, TOTAL over the catalogue, and band index never decreases as capacityTier rises', () => {
  const th = LOCAL.densityBandMagnitudeThresholds;
  assert.ok(Array.isArray(th) && th.length > 0);
  for (let i = 1; i < th.length; i++) {
    assert.ok(th[i].minMagnitude > th[i - 1].minMagnitude, `thresholds must be strictly ascending at ${th[i].band}`);
  }
  const bandIndex = (b) => th.findIndex((x) => x.band === b);
  for (const band of new Set(Object.values(LOCAL.landUseDensityMapping))) {
    assert.ok(bandIndex(band) >= 0, `band "${band}" used by landUseDensityMapping has no threshold entry`);
  }
  let checked = 0;
  for (const [id, sp] of Object.entries(SPECS)) {
    if (sp.residents == null && sp.jobs == null) continue;
    let prev = -1;
    for (let tier = 0; tier < 10; tier++) {
      const band = landUseDensityBandFor(id, tier);
      const i = bandIndex(band);
      assert.ok(i >= 0, `${id} at tier ${tier} resolved to band "${band}", which is not in densityBandMagnitudeThresholds`);
      assert.ok(i >= prev, `${id}: band index must never DECREASE as capacityTier rises (tier ${tier} -> ${band})`);
      prev = i;
      checked++;
    }
  }
  assert.ok(checked >= 400, `expected the whole residents/jobs catalogue x 10 tiers, checked ${checked}`);
});

test('round2 (BUG-988 residual): realisedCityWideModeShareOf never aliases a live table row across states, including the zero-demand fallback', () => {
  // NOTE (finding filed this round): unlike perTileLocalModeShareOf's
  // vectors, the object realisedCityWideModeShareOf returns is NOT frozen
  // and IS the memoised object for that state, so a caller mutating it
  // poisons that state's own later reads. Cross-state and cross-table
  // safety — the part that matters for correctness today — is what this
  // pin holds; the freeze is the filed follow-up.
  const mkEmpty = () => board([b(1, 'road', 10, 10)], 0);
  const a = mkEmpty();
  assert.equal(demandForecastOf(a).length, 0, 'fixture precondition: zero demand tiles');
  const cityBefore = modeShareOf(ladderPointOf(a)).car;
  realisedCityWideModeShareOf(a).car = -1;
  assert.equal(modeShareOf(ladderPointOf(mkEmpty())).car, cityBefore, 'the zero-demand fallback must not hand out (and let a caller corrupt) a shared city row');
  const b1 = board([b(1, 'res_hut', 80, 80), b(2, 'rail', 80, 81)], 50);
  const b2 = board([b(1, 'res_hut', 80, 80), b(2, 'rail', 80, 81)], 50);
  const v1 = perTileLocalModeShareOf(b1).get('80,80');
  assert.ok(Object.isFrozen(v1), 'per-tile vectors must stay frozen');
  assert.throws(() => { v1.car = 999; });
  assert.equal(perTileLocalModeShareOf(b2).get('80,80').car, v1.car, 'a different state must read an uncorrupted row');
});

test('round2: land-use MIX at identical population moves the realised split (build sensitivity beyond the rail/no-rail pair)', () => {
  const pop = 2000;
  const lowRise = realisedCityWideModeShareOf(board([b(1, 'res_hut', 80, 80), b(2, 'res_hut', 82, 82)], pop));
  const highRise = realisedCityWideModeShareOf(board([b(1, 'res_tower_sgp', 80, 80), b(2, 'off_tower', 82, 82)], pop));
  assert.notDeepEqual(lowRise, highRise, 'two cities at the SAME population with different land use must not share a realised split');
  assert.ok(highRise.car < lowRise.car, `a dense land-use mix must have a lower realised car share (${highRise.car}) than a low-rise one (${lowRise.car})`);
});
